name: dev-fastdfe
channels:
  - conda-forge
dependencies:
  - dadi
  - r-base
  - rpy2
  - r-rjsonio
  - r-irkernel
  - jupyterlab
  - pip
  - pip:
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-sugar
    - pytest-pycharm
    - -r requirements_testing.txt