name: dev-fastdfe
dependencies:
  - python=3.10
  - dadi
  - r-base
  - rpy2
  - r-rjsonio
  - r-irkernel
  - r-usethis
  - r-devtools
  - jupyterlab
  - jupyter
  - pip
  - pip:
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-sugar
    - pytest-pycharm
    - -r requirements_testing.txt