name: dev-fastdfe
channels:
  - conda-forge
dependencies:
  - python=3.12
  - dadi
  - r-base
  - rpy2
  #- r-rjsonio
  - r-irkernel
  - r-usethis
  - r-devtools
  - jupyterlab
  - jupyter
  - codecov
  - pip
  - pip:
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-sugar
    - pytest-pycharm
    - -r requirements_testing.txt