name: dev-fastdfe
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.12
  - typing-extensions>=4.5.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.9.3
  - jsonpickle>=3.0.0
  - multiprocess>=0.70.12
  - pyyaml>=6.0
  - cyvcf2>=0.30.9
  - pyfaidx>=0.7.1
  - tqdm>=4.60.0
  - mpmath>=1.3.0
  - dadi
  - r-base
  - rpy2
  - r-rjsonio
  - pytest-xdist
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - myst-nb
  - jupyter
  - poetry
  - python-dotenv
  - pip
  - pip:
    - pytest-pycharm