"""
Infer the DFE from spectra generated by SLiM.
"""

__author__ = "Janek Sendrowski"
__contact__ = "sendrowski.janek@gmail.com"
__date__ = "2024-02-26"

import numpy as np
from matplotlib import pyplot as plt

try:
    import sys

    # necessary to import fastdfe locally
    sys.path.append('..')

    testing = False
    sfs_file = snakemake.input[0]
    full_dfe = snakemake.params.get('full_dfe')
    out_summary = snakemake.output.summary
    out_serialized = snakemake.output.serialized
    out_dfe = snakemake.output.get('dfe', None)
    out_model_fit = snakemake.output.get('model_fit', None)
    out_spectra = snakemake.output.get('spectra', None)
    out_params = snakemake.output.get('params', None)
except NameError:
    # testing
    testing = True
    sfs_file = 'results/slim/n_replicate=1/n_chunks=100/g=1e4/L=1e7/mu=1e-8/r=1e-7/N=1e3/s_b=1e-9/b=5/s_d=3e-1/p_b=0/n=100/folded/sfs.csv'
    full_dfe = True
    out_summary = "scratch/summary.json"
    out_serialized = "scratch/serialized.json"
    out_dfe = "scratch/dfe.png"
    out_model_fit = "scratch/model_fit.png"
    out_spectra = "scratch/spectra.png"
    out_params = "scratch/params.png"

import fastdfe as fd

s = fd.Spectra.from_file(sfs_file)

# create from config
inf = fd.BaseInference(
    sfs_neut=s['neutral'],
    sfs_sel=s['selected'],
    do_bootstrap=True,
    parallelize=True,
    n_runs=100,
    fixed_params=dict(all=dict(eps=0) | dict(p_b=0, S_b=1) if not full_dfe else {})
)

# perform inference
inf.run()

# save object in serialized form
inf.to_file(out_serialized)

# save summary
inf.get_summary().to_file(out_summary)

params = {k: v for k, v in inf.bootstraps.mean().to_dict().items() if k not in ['alpha']}

params_str = dict(
    S_d=f"{params['S_d']:.0f}",
    b=f"{params['b']:.2f}",
    p_b=f"{params['p_b']:.2f}",
    S_b=f"{params['S_b']:.1f}",
    eps=f"{params['eps']:.2f}"
)

# plot results
inf.plot_inferred_parameters(file=out_params, show=testing)
inf.plot_sfs_comparison(file=out_model_fit, show=testing)

fig, ax = plt.subplots(figsize=(4.5, 2.2))
plt.rcParams['axes.titlesize'] = 11

inf.plot_discretized(
    file=out_dfe,
    show=testing,
    title="Inferred DFE\n" + ", ".join([f"${k}$={v}" for k, v in params_str.items()]),
    intervals=[-np.inf, -100, -10, -1, 1, np.inf],
    ax=ax
)
s.plot(file=out_spectra, show=testing)

pass
