# This workflow will install Python dependencies, and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests for local package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    name: run tests on linux for local package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: "3.10"
          environment-file: snakemake/envs/testing.yaml
          auto-activate-base: false
          activate-environment: testing-fastdfe
      - run: |
          pytest testing/ -n 9