name: Run tests on different OS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    name: run tests on ${{ matrix.os }} with Python ${{ matrix.python-version }} for local package
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12" ]  # Add this line
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2  # Use this action to set up Python
        with:
          python-version: ${{ matrix.python-version }}  # Specify the Python version here
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}  # Specify the Python version here
          environment-file: snakemake/envs/testing.yaml
          auto-activate-base: false
          activate-environment: testing-fastdfe
      - run: |
          pytest testing/
