name: Run tests on different OS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    name: run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: snakemake/envs/testing.yaml
        auto-activate-base: false
        activate-environment: testing-fastdfe
    - run: |
          pytest testing/
    - uses: codecov/codecov-action@v3
